### ISSUE TITLE
Run this with Wine?

### ISSUE THREAD

**Issue by lothar-cell** [TheIndra55/Yura#2]
Is there any way to run this with Wine? .NET 6 Desktop Runtime is installed, but the installation of Yura.exe hangs.

**Comment by TheIndra55** [comment]
Hi,

I'm unsure why it doesn't work, do you know if other applications using the .NET Desktop Runtime work? Sadly I'm unable to be much of help since I don't have a Linux machine to debug this myself.

**Comment by lothar-cell** [comment]
Thanks for getting back, at the end I installed it under a Win VM, all working fine. Cheers!

**Comment by TheIndra55** [comment]
Closing this, might debug it in the future.
